name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        java: [ 8, 11, 17 ]
        exclude:
          - os: macos-latest
            java: 8
          - os: macos-latest
            java: 17
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.6.0

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}

      - if: runner.os == 'Linux'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install flac sox

      - if: runner.os == 'macOS'
        run: |
          brew install flac sox

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build --warning-mode all
